#!/usr/bin/env fish

set file fish_prompt.fish
set dir $HOME/.config/fish/functions/

if test -f $dir$file
    rm -rf $dir$file
    cd $dir
    wget https://raw.githubusercontent.com/wolf-theme/fish-shell/master/fish_prompt.fish
end